language: scala
scala:
   - 2.12.14
   - 2.13.6

jdk:
 - oraclejdk8

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt

script:
  - sbt ++$TRAVIS_SCALA_VERSION 'project delight' clean coverage test coverageReport;

after_success:
  - bash <(curl -s https://codecov.io/bash)
