name: CI
on:
  push:

jobs:
  jvm:
    strategy:
      fail-fast: true
      matrix:
        java: [11, 16]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: olafurpg/setup-scala@v13
        with:
          java-version: "adopt@1.${{ matrix.java }}"
      - run: sbt +test
